Name : RIZA JAMES PETER

ASSIGNMENT NO:06 Data Analytics III
1. Implement Simple Naïve Bayes classification algorithm using Python/R on iris.csv dataset.
2. Compute Confusion matrix to find TP, FP, TN, FN, Accuracy, Error rate, Precision, Recall
on the given dataset.

In [ ]:
#Step1: Loading the Required packages
import seaborn as sns
import numpy as np

In [ ]:
#Step 2:Loading the dataset
data = sns.load_dataset('iris')

In [ ]:
data.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [ ]:
#Step 3:Checking for null values
data.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

There is no missing values. Hence preprocessing to handle missing values is not required.

In [ ]:
#Step 4:Importing required libraries for model building
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB

In [ ]:
#Step 5: Extract the predictors and the target variables
X = data[['sepal_length', 'sepal_width']]
y = data['species']

In [ ]:
#Step 6: Splitting the dataset
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=2)

In [ ]:
#Step 7: Feature scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [ ]:
 #Step 8: Fitting the naive bayes classifier
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(x_train,y_train)

GaussianNB()

In [ ]:
y_pred = classifier.predict(x_test)

Compute Confusion matrix to find TP, FP, TN, FN, Accuracy, Error rate, Precision, Recall
on the given dataset.

In [ ]:
#Step 9: Performance
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score

cm = confusion_matrix(y_test,y_pred)
print(cm)

[[11  3  0]
 [ 0  5  3]
 [ 0  0  8]]


In [ ]:
# Step 10: Compute TP, FP, TN, FN
total = np.sum(cm)
#print(total)
TP = cm[0,0]
print(TP)
TN = cm[1,1]
print(TN)

11
5


In [ ]:
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:",accuracy)

Accuracy: 0.8


In [ ]:
# Compute error rate
error_rate = 1 - accuracy

In [ ]:
# Compute precision
precision = precision_score(y_test, y_pred, average='weighted')


In [ ]:
# Compute recall
recall = recall_score(y_test, y_pred, average='weighted')

In [ ]:
# Print confusion matrix and performance metrics
print("True Positives:", TP)
print("False Positives:", FP)
print("True Negatives:", TN)
print("False Negatives:", FN)
print("Accuracy:", accuracy)
print("Error Rate:", error_rate)
print("Precision:", precision)
print("Recall:", recall)

True Positives: 11
False Positives: 3
True Negatives: 5
False Negatives: 0
Accuracy: 0.8
Error Rate: 0.19999999999999996
Precision: 0.8272727272727274
Recall: 0.8
